name: 'node matrix'
description: 'Output a JSON matrix of node versions to run in CI'
author: ljharb
inputs:
  version_key:
    description: 'key in JSON output to contain versions'
    required: false
    default: 'node-version'
  requireds:
    description: 'semver range for required versions'
  optionals:
    description: 'semver range for optional versions'
  empty:
    description: 'if true, preset is ignored and an empty list is returned'
    required: false
    default: false
  preset:
    description: 'optional preset, takes precedence over requireds/optionals'
  notable:
    description: 'semver range for notable versions, that should be pulled from "preset" into "required"'
  type:
    description: 'majors, or minors?'
    choices: ['majors', 'minors']
  envs:
    description: 'optional env variables to add to the matrix'
    required: false
  versionsAsRoot:
    description: 'ignore the version_key, and make the versions be the root of the outputs?'
    required: false
outputs:
  requireds:
    description: 'JSON object containing required-to-pass versions'
  optionals:
    description: 'JSON object containing allowed-to-fail versions'
runs:
  using: node20
  main: ./index.js
