name: 'node CI: check package version, for publishing'
description: 'check the package.json version against the npm registry'
author: ljharb
inputs:
  path:
    required: false
    description: 'Path to the npm package'
    default: '.'
outputs:
  committed-version:
    description: 'Version now commited to the repo'
  published-version:
    description: 'Latest version published to npm, based on `dist-tags`'
  is-new-version:
    description: 'Whether repo version is yet new to npm (`"true"` or `"false"`)'
runs:
  using: node20
  main: ./index.mjs
branding:
    icon: 'loader'
    color: 'orange'
