name: 'node CI run a command'
description: 'Run a given command on a given node version'
author: ljharb
inputs:
  node-version:
    description: 'version of node to use via nvm'
    required: false
    default: 'lts/*'
  command:
    description: '`npm run` command'
  shell-command:
    description: shell command, mutually exclusive with `command`
  cache-node-modules-key:
    description: 'if provided, cache node_modules under this cache key'
    required: false
    default: ''
  skip-install:
    description: 'skip `npm install` step'
    default: false
  before_install:
    description: 'command to run before `npm install`'
    required: false
  after_install:
    description: 'command to run after `npm install`'
    required: false
  after_success:
    description: 'command to run after everything succeeds. default runs codecov'
    required: false
  skip-ls-check:
    description: 'skip the `npm ls` check (not recommended)'
    required: false
    default: false
  use-npm-ci:
    description: 'if true, will use `npm ci` instead of `npm install`'
    required: false
    default: false
runs:
  using: node16
  main: ./index.js
  post: ./post.js
