name: "node index cache"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cache:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        kind:
          - nodejs
          - iojs

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443
            raw.githubusercontent.com:443
            nodejs.org:443
            iojs.org:443
            actions-results-receiver-production.githubapp.com:443
      - uses: ljharb/actions/node/install@main
        with:
          node-version: "lts/*"
          skip-install: true
          skip-ls-check: true
          skip-latest-npm: true
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.kind }}
      - run: curl -O -J "https://${{ matrix.kind }}.org/dist/index.tab"
      - run: curl -O -J "https://${{ matrix.kind }}.org/dist/index.json"
      - run: git diff && git status
      - name: commit changes
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: "curl \"https://${{ matrix.kind }}.org/dist/index.tab\" (and .json)"

  finisher:
    runs-on: ubuntu-latest
    needs: [cache]

    steps:
      - run: true
