on:
  workflow_call:
    inputs:
      command:
        description: '`run:` step'
        required: true
        type: string
      timeout-minutes:
        required: false
        type: number
        default: 30

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  notable-esm:
    name: 'notable ESM minors'
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 'lts/*'
          - node-version: '14.13'
          - node-version: '13.7'
          - node-version: '12.20'
          - node-version: '12.17'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v3
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          cache-node-modules-key: node_modules-${{ github.workflow }}-${{ github.action }}-${{ github.run_id }}
          skip-ls-check: false
      - run: ${{ inputs.command }}
      - uses: codecov/codecov-action@v3

  node:
    name: 'node, notable ESM minors'
    needs: [notable-esm]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - run: 'echo tests completed'
