on:
  workflow_call:
    secrets:
      token:
        description: 'Github Token'
        required: true

jobs:
  _:
    name: "Automatic Rebase"

    runs-on: ubuntu-latest

    permissions:
      contents: write  # for ljharb/rebase to push code to rebase
      pull-requests: read  # for ljharb/rebase to get info about PR

    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: ljharb/rebase@master
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
