on:
  workflow_call:
    inputs:
      committer-date-is-author-date:
        description: 'Whether to pass --committer-date-is-author-date to git rebase (true/false).'
        type: boolean
        required: false
        default: false
    secrets:
      token:
        description: 'Github Token'
        required: true

cache-mode: none

jobs:
  _:
    name: "Automatic Rebase"

    runs-on: ubuntu-24.04

    permissions:
      contents: write  # for ljharb/rebase to push code to rebase
      pull-requests: read  # for ljharb/rebase to get info about PR

    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: true
        show-progress: false

    - uses: ljharb/rebase@master
      with:
        committer-date-is-author-date: ${{ inputs.committer-date-is-author-date }}
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
