name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create a release from"
        required: true
jobs:
  release:
    if: github.event.repository.fork == false

    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints:
            api.github.com:443
            raw.githubusercontent.com:443
            github.com:443

      - name: Get version from tag
        id: tag_name
        run: echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: validate semver pattern
        env:
          VERSION: ${{ steps.tag_name.outputs.current_version }}
        run: npx semver "${VERSION}"

      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          show-progress: false

      - uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ steps.tag_name.outputs.current_version }}

      - name: Get common links from changelog
        id: changelog
        run: |
          # Parse the changelog for common links
          _links="$(grep -P '^\[.*]:.+' ${GITHUB_WORKSPACE}/CHANGELOG.md | sort -u)"
          _links="${_links//'%'/'%25'}"
          _links="${_links//$'\n'/'%0A'}"
          _links="${_links//$'\r'/'%0D'}"
          # Set output 'links' to $_links
          echo "links=${_links}" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog_reader.outputs.changes }}
            ${{ steps.changelog.outputs.links }}

